---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: helm-release-ingress-traefik
  namespace: ingress-traefik
  labels:
    app: ingress-traefik
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: traefik
      version: "29.0.1"
      sourceRef:
        kind: HelmRepository
        name: helm-repo-traefik
      interval: 5m
  releaseName: ingress-traefik
  valuesFrom:
    - kind: ConfigMap
      name: traefik-values
      valuesKey: traefik-values.yaml
